### ISSUE TITLE
Can it forward the data somehow?

### ISSUE THREAD

**Issue by harshilishere** [tobozo/ESP32-USB-Soft-Host#11]
This may be a duplicate question. I am trying to identify from your git repo if it is possible to read the usb device details(which it does) and then also forward the data as it is to computer?
i.e.: I connect a mouse to esp32(via usb) and then get the data coming from the mouse in esp and forward it serially to let's say my computer? or why not forward the data to computer via mqtt!?

So in one line the question is "Can it send and receive the data from and to the usb device connected??"

**Comment by tobozo** [comment]
In the [example code](https://github.com/tobozo/ESP32-USB-Soft-Host/blob/main/examples/USB_Test/), customizable callbacks are attached for both USB detection and data, it shouldn't be a problem to implement your data forwarding logic in there.
