### ISSUE TITLE
MIDI support

### ISSUE THREAD

**Issue by MaximKotliar** [tobozo/ESP32-USB-Soft-Host#19]
Hi, will USB-MIDI device works?

**Comment by tobozo** [comment]
hi,

[probably not](https://github.com/sdima1357/esp32_usb_soft_host/issues/2), however [there may be some unexplored charts](https://www.kvraudio.com/forum/viewtopic.php?t=547423) if you happen to be the owner of an ancient midi keyboard using USB Low Speed (or customised to).
