### ISSUE TITLE
Sending Print data to Thermal printer controlled by ESP32 via HID .

### ISSUE THREAD

**Issue by Vineeth-B007** [tobozo/ESP32-USB-Soft-Host#25]
Dear sir, 
My device is a thermal printer with an ESP32 controller. In that case, I have to send the print data from a 3rd party exe to my printer via the HID port. As per your tested H/W devices, the library is compatible with certain mice and keyboards. Is there any support for printers, mainly 3/2-inch thermal printers? 
Any help would be great.

Regards,
Vineeth B

**Comment by tobozo** [comment]
hi,

thermal printers aren't HID, and this library only supports HID devices.

closing this issue as out of scope
