### ISSUE TITLE
how import  freertos ?

### ISSUE THREAD

**Issue by doudousha** [tobozo/ESP32-USB-Soft-Host#26]
Esp32 C3
I'm trying to compile with arduino ide
d:\arduino\libraries\ESP32-USB-Soft-Host\src/usb_host.h:4:10: fatal error: freertos/FreeRTOS.h: No such file or directory
    4 | #include "freertos/FreeRTOS.h"

**Comment by tobozo** [comment]
bad platformio cache maybe ?

ESP32-C3 has no history with this error message so it's more likely a problem with the environment,

With platformio, purging  the `%userprofile%/.platformio` folder can solve some issues.

With Arduino IDE reinstalling the esp32 board package to the latest version (2.0.5) can also improve things.

**Comment by doudousha** [comment]
![image](https://user-images.githubusercontent.com/3984224/197366968-bc78542b-435d-4c1c-803d-5f1c14356f42.png)

**Comment by tobozo** [comment]
From the file name in your tab it looks like you're using a partial copy of the example, but that example is composed of two files:

![image](https://user-images.githubusercontent.com/1893754/197380649-78948d11-4537-4e23-926f-0d974ffed0b5.png)

Also arduino IDE claims it's library version 0.1.2 but the error message you have indicates it's neither 0.1.1 nor 0.1.2, did you install it from the library manager?

With ESP32-C3 you should only see this warning message during compilation: 

```log
#pragma message "memory protection features disabled, templated asm nop() will be used"
```
I'm not sure where you got this `Error: memory prot must be disabled` message from, but it's not part of this repository, 
The full compilation log could provide more clues about that inconsistency.

If it can be of any help, these are the settings I've used to test the compilation:

![image](https://user-images.githubusercontent.com/1893754/197381071-acecc1b4-d6c4-4a9a-8169-1abedf71c3a6.png)

```log
Sketch uses 266144 bytes (20%) of program storage space. Maximum is 1310720 bytes.
Global variables use 15556 bytes (4%) of dynamic memory, leaving 312124 bytes for local variables. Maximum is 327680 bytes.
```

**Comment by doudousha** [comment]
thank you man,
I don't know where to set in arduino

sdima1357/esp32_usb_soft_host  
only for esp32c3: Component config-> ESP System Setting -> Memory protection-> Disable.

usb_test/main/usb_host.c 
line 244  : memory prot must be disabled

![image](https://user-images.githubusercontent.com/3984224/197466308-018f849d-95bf-4e47-8ecf-e1bf88a054f7.png)

**Comment by tobozo** [comment]
the release is now propagated in the [library registry](https://www.arduinolibraries.info/libraries/esp32-usb-soft-host) and consecutively available in the Arduino Library Manager

please let me know if this solved the issue for you
