### ISSUE TITLE
cpu freqency promble

### ISSUE THREAD

**Issue by gaojingqi23** [tobozo/ESP32-USB-Soft-Host#27]
The board that i used is ESP32 DEVKIT V1,when i set the cpu frequency 80MHz,USB Test failed. I wasted several hours to find problems, finally i tried to change cpu_freq, 240MHz and 160MHz were successfully ! But I when was trying 80MHz again, it failed. I don't konw it is just only my problem or there is a request to set cpu_freq bigger.

**Comment by tobozo** [comment]
240MHz no less (it's for ESP32, not ESP8266), it's surprising you had results at 160MHz though

**Comment by gaojingqi23** [comment]
> 240MHz no less (it's for ESP32, not ESP8266), it's surprising you had results at 160MHz though

thank you for replying
