### ISSUE TITLE
support for wireless keyboards?

### ISSUE THREAD

**Issue by jayesh312001** [tobozo/ESP32-USB-Soft-Host#9]
the library successfully worked for wired keyboards but can we make it work out for wireless keyboards as well? i'm using logitech mk215 wireless keyboard and it's not working.

**Comment by tobozo** [comment]
> i'm using logitech mk215 wireless keyboard and it's not working.

That's not surpsising, most usb dongles for wireless keyboard/mouse aren't using USB-LS.

If you happen to find one that works, please reopen this issue and provide the vendorID / productID so I can add it to the supported list, but it's very unlikely.

thanks for your feedback :+1:
